from app.database import db

def analyze_transaction(transaction_id: str):
    tx = db.get_transaction(transaction_id)
    if not tx:
        raise ValueError(f"Transaction {transaction_id} not found")
        
    events = db.get_events_for_transaction(transaction_id)
    settlement = db.get_settlement_for_transaction(transaction_id)
    
    if not events:
        return {"status": "NO_EVENTS_FOUND"}
        
    # 1. Sort events chronologically (actual timestamps from the DB)
    sorted_events = sorted(events, key=lambda x: x["timestamp"])
    
    # 2. Extract Data
    expected = tx.get("expected_receiver_account_id")
    actual = settlement.get("actual_account_id") if settlement else None
    
    # Derive mismatch condition from raw data comparison
    has_routing_mismatch = (expected is not None and actual is not None and expected != actual)
    
    upstream_anomaly = None
    downstream_consequences = []
    normal_events = []
    
    # 3. Dynamic Causal Chain Engine
    for evt in sorted_events:
        metadata = evt.get("metadata", {}) or {}
        
        # Check if this specific event introduces a routing mismatch
        event_actual_account = metadata.get("actual_account") or metadata.get("routed_to")
        introduces_mismatch = False
        if event_actual_account and expected:
            if event_actual_account != expected:
                introduces_mismatch = True
                
        # Detect anomaly dynamically based on state, severity, or data mismatch
        is_anomalous = (
            evt.get("severity") in ["CRITICAL", "ERROR"] or 
            evt.get("status") == "FAILED" or 
            introduces_mismatch
        )
        
        if not upstream_anomaly and is_anomalous:
            upstream_anomaly = evt
        elif upstream_anomaly:
            # Events that occur AFTER the upstream anomaly are consequences
            if evt.get("status") == "FAILED" or evt.get("severity") in ["WARNING", "ERROR"]:
                downstream_consequences.append(evt)
        else:
            normal_events.append(evt)
            
    # Compile textual evidence
    evidence = []
    if has_routing_mismatch:
        evidence.append("Payment capture succeeded in precursors")
        evidence.append("Expected receiver differs from actual settlement destination")
        evidence.append(f"Routing anomaly ({upstream_anomaly['event_type']}) occurred strictly before downstream failures")
        if any(e['event_type'] == 'WEBHOOK_REJECTED' for e in downstream_consequences):
            evidence.append("Webhook was subsequently rejected by expected receiver")
        if any(e['event_type'] == 'RECEIVER_NOT_CREDITED' for e in downstream_consequences):
            evidence.append("Receiver platform confirmed funds were not credited")
            
    # Compile recommendation
    if has_routing_mismatch:
        recommendation = (
            "1. Verify and correct the settlement-account mapping.\n"
            "2. Reconcile the captured payment against the actual settlement destination.\n"
            "3. Reprocess and reconcile the failed receiver credit."
        )
    else:
        recommendation = "Recommendation not yet generated by the current RECON engine."

    return {
        "transaction_id": transaction_id,
        "causal_derivation": {
            "routing_mismatch_detected": has_routing_mismatch,
            "expected_destination": expected,
            "actual_destination": actual,
        },
        "incident_analysis": {
            "root_upstream_anomaly": upstream_anomaly,
            "downstream_consequences": downstream_consequences,
            "healthy_precursors": normal_events
        },
        "root_cause": upstream_anomaly['message'] if upstream_anomaly else "No root cause identified",
        "evidence": evidence,
        "recommendation": recommendation,
        "confidence": "HIGH" if upstream_anomaly and has_routing_mismatch else "LOW"
    }
